apiVersion: apps/v1
kind: Deployment
metadata:
  name: naga-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: naga-springboot
  template:
    metadata:
      labels:
        app: naga-springboot
    spec:
      containers:
        - name: springboot
          image: kandula435/docker-web-demo:docker-web-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: naga-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: naga-springboot
